## [Numpy Tutorial](https://numpy.org/)

- NumPy is a library for the Python programming language, adding support for large, multi-dimensional arrays and matrices, along with a large collection of high-level mathematical functions to operate on these arrays.

In [1]:
import numpy as np

### [np.zeros](https://docs.scipy.org/doc/numpy/reference/generated/numpy.zeros.html)

$$np.zeros(shape, dtype=float, order='C')$$

- Return a new array of given shape and type, **filled with zeros.**

In [17]:
one_d = np.zeros(3)
print("1-D Array of Zeros: ",'\n',one_d)
print("Shape of 1-D Array: ",one_d.shape)
print()

two_d = np.zeros((3,3))
print("2-D Array of Zeros: ",'\n',two_d)
print("Shape of 2-D Array: ",two_d.shape)
print()


three_d = np.zeros(((3,3,3)))
print("3-D Array of Zeros: ",'\n',three_d)
print("Shape of 3-D Array: ",three_d.shape)

1-D Array of Zeros:  
 [0. 0. 0.]
Shape of 1-D Array:  (3,)

2-D Array of Zeros:  
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Shape of 2-D Array:  (3, 3)

3-D Array of Zeros:  
 [[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]
Shape of 3-D Array:  (3, 3, 3)


### [np.ones](https://docs.scipy.org/doc/numpy/reference/generated/numpy.ones.html)

$$np.ones(shape, dtype=None, order='C')$$
- Return a new array of given shape and type, filled with ones.

In [18]:
one_d = np.ones(3)
print("1-D Array of Ones: ",'\n',one_d)
print("Shape of 1-D Array: ",one_d.shape)
print()

two_d = np.ones((3,3))
print("2-D Array of Ones: ",'\n',two_d)
print("Shape of 2-D Array: ",two_d.shape)
print()


three_d = np.ones(((3,3,3)))
print("3-D Array of Ones: ",'\n',three_d)
print("Shape of 3-D Array: ",three_d.shape)

1-D Array of Ones:  
 [1. 1. 1.]
Shape of 1-D Array:  (3,)

2-D Array of Ones:  
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
Shape of 2-D Array:  (3, 3)

3-D Array of Ones:  
 [[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]
Shape of 3-D Array:  (3, 3, 3)


### [np.arange](https://docs.scipy.org/doc/numpy/reference/generated/numpy.arange.html)

- **np.arange([start, ]stop, [step, ]dtype=None)**

Return evenly spaced values within a given interval.

Values are generated within the half-open interval [start, stop) (in other words, the interval including start but excluding stop). For integer arguments the function is equivalent to the Python built-in range function, but returns an ndarray rather than a list.

**When using a non-integer step, such as 0.1, the results will often not be consistent. It is better to use numpy.linspace for these cases.**

In [5]:
print("Creation of an Array from 1-9:",np.arange(1,10))
print()
print("Creation of an Array from 1-9 with step = 2:",np.arange(1,10,2))
print()
print("Creation of an Array from 0-9 :",np.arange(10))


Creation of an Array from 1-9: [1 2 3 4 5 6 7 8 9]

Creation of an Array from 1-9 with step = 2: [1 3 5 7 9]

Creation of an Array from 0-9 : [0 1 2 3 4 5 6 7 8 9]


### [np.linspace](https://docs.scipy.org/doc/numpy/reference/generated/numpy.linspace.html)

- **np.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0)**

- Return evenly spaced numbers over a specified interval.

Returns num evenly spaced samples, calculated over the interval [start, stop].

The endpoint of the interval can optionally be excluded.

In [18]:
print("array of 1-2, Including Endpoint ",np.linspace(1,2,num=5,endpoint=True))
print()
print("array of 1-11, Excluding Endpoint ",np.linspace(1,11,num=10,endpoint=False))
print()
print("array of 1-2, Including Endpoint ",np.linspace(1,2,num=5,endpoint=True,retstep=True))
print()


array of 1-2, Including Endpoint  [1.   1.25 1.5  1.75 2.  ]

array of 1-2, Including Endpoint  [ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]

array of 1-2, Including Endpoint  (array([1.  , 1.25, 1.5 , 1.75, 2.  ]), 0.25)



### [np.reshape](https://docs.scipy.org/doc/numpy/reference/generated/numpy.reshape.html)

- **np.reshape(a, newshape, order='C')**

- Gives a new shape to an array without changing its data.

In [25]:
## Let's create a 1-D Array using np.arange and then reshape it.

x = np.arange(9)
print("Initial 1-D Array:",'\n',x)
print("The Shape of Array is:",'\n',x.shape)
x_ = np.reshape(x,(3,3))
print("Modified Array :",'\n',x_)
print("Shape of modified Array :",'\n',x_.shape)

## NOTE : The number of elements in the Initial array must alwyas be equal to the product of the integers of new shape:
## here number of elements = 9 
## And new desired shape is = 3,3  (Product of these two is 9)

## Take Another Example:
print()
x = np.arange(10)
print("Initial 1-D Array:",'\n',x)
print("The Shape of Array is:",'\n',x.shape)
x_ = np.reshape(x,(2,5))
print("Modified Array :",'\n',x_)
print("Shape of modified Array :",'\n',x_.shape)

## 10 elements = 2,5 shape.

Initial 1-D Array: 
 [0 1 2 3 4 5 6 7 8]
The Shape of Array is: 
 (9,)
Modified Array : 
 [[0 1 2]
 [3 4 5]
 [6 7 8]]
Shape of modified Array : 
 (3, 3)

Initial 1-D Array: 
 [0 1 2 3 4 5 6 7 8 9]
The Shape of Array is: 
 (10,)
Modified Array : 
 [[0 1 2 3 4]
 [5 6 7 8 9]]
Shape of modified Array : 
 (2, 5)
