## [Numpy Tutorial](https://numpy.org/)

- NumPy is a library for the Python programming language, adding support for large, multi-dimensional arrays and matrices, along with a large collection of high-level mathematical functions to operate on these arrays.

In [1]:
import numpy as np

In [6]:
print("1-D Array of Zeros: ",np.zeros(3))
print("2-D Array of Zeros: ",'\n',np.zeros((3,3)))

1-D Array of Zeros:  [0. 0. 0.]
2-D Array of Zeros:  
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])